spring.datasource.url=jdbc:mysql://localhost:3306/billing_app
spring.datasource.username=anish
spring.datasource.password=AdaGoat#707
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/api/v1.0